//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Environment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Environment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingBot.Environment", typeof(Environment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123 Fake Street.
        /// </summary>
        internal static string address1 {
            get {
                return ResourceManager.GetString("address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string address2 {
            get {
                return ResourceManager.GetString("address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04.
        /// </summary>
        internal static string cardExpiryMonth {
            get {
                return ResourceManager.GetString("cardExpiryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string cardExpiryYear {
            get {
                return ResourceManager.GetString("cardExpiryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4758 7475 5647 3432.
        /// </summary>
        internal static string cardNumber {
            get {
                return ResourceManager.GetString("cardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 435.
        /// </summary>
        internal static string cardSecurityCode {
            get {
                return ResourceManager.GetString("cardSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jackets.
        /// </summary>
        internal static string desiredCategoryName {
            get {
                return ResourceManager.GetString("desiredCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Blue.
        /// </summary>
        internal static string desiredItemColour {
            get {
                return ResourceManager.GetString("desiredItemColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piping Track Jacket.
        /// </summary>
        internal static string desiredItemName {
            get {
                return ResourceManager.GetString("desiredItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to johnsmith@hotmail.com.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Smith.
        /// </summary>
        internal static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07494 746356.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD2 222.
        /// </summary>
        internal static string postcode {
            get {
                return ResourceManager.GetString("postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.supremenewyork.com/shop/all.
        /// </summary>
        internal static string siteURL {
            get {
                return ResourceManager.GetString("siteURL", resourceCulture);
            }
        }
    }
}
